Settings As screen:
    Fill: =ColorValue(varThemeColors.background)

    conContent_Settings As groupContainer.verticalAutoLayoutContainer:
        Fill: =ColorValue(varThemeColors.backgroundFill)
        Height: =Parent.Height*.75
        LayoutAlignItems: =LayoutAlignItems.Center
        LayoutDirection: =LayoutDirection.Vertical
        LayoutGap: =20
        LayoutMode: =LayoutMode.Auto
        LayoutOverflowY: =LayoutOverflow.Scroll
        PaddingLeft: |-
            =Switch(App.ActiveScreen.Size,
            5, (Parent.Width - 1450)/2,
            4, 75,
            3, 50,
            2, 25,
            1, 10
            )
        PaddingRight: =Self.PaddingLeft
        Width: =Parent.Width*.96
        X: =Parent.Width*.02
        Y: =compHeader_Settings.Height+conPrompt_Settings.Height
        ZIndex: =1

        lblSubtitle_Settings As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =ColorValue(varThemeColors.text)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            FocusedBorderColor: =ColorValue(varThemeColors.primary)
            FocusedBorderThickness: =4
            Font: =varThemeFont.H2.face
            FontWeight: =varThemeFont.H2.weight
            Height: =75
            Italic: =varThemeFont.H2.italic
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            PaddingBottom: =0
            PaddingLeft: =40
            PaddingTop: =0
            Role: =TextRole.Heading2
            Size: =varThemeFont.H3.size
            Text: |-
                =// Define a variable named "Text" with the value "{value}"
                With(
                    {Text: "Color Mode"},
                    // Check if a localized text exists for "Text" in the user's preferred language
                    If(
                        // If the localized text is blank, return the default text
                        IsBlank(
                            LookUp(
                                colUserLocalizedStrings,
                                'English Value' = Text 
                            ).'Localized Value'
                        ),
                        Text,
                        // If a localized text is found, return that instead of the default text
                        LookUp(
                            colUserLocalizedStrings,
                            'English Value' = Text 
                        ).'Localized Value'
                    )
                )
            VerticalAlign: =VerticalAlign.Bottom
            Width: =594
            ZIndex: =1

        compThemeSettings_Settings As compThemeSettings:
            BlockWidth: =Parent.Width/3
            Height: =compThemeSettings_Settings.SettingsHeight
            LayoutMinHeight: =640
            LayoutMinWidth: =640
            SettingsWidth: =Parent.Width
            Width: =compThemeSettings_Settings.SettingsWidth
            ZIndex: =4

    conPrompt_Settings As groupContainer.verticalAutoLayoutContainer:
        Height: =lblPromptTitle_Settings.Height
        LayoutAlignItems: =LayoutAlignItems.Center
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        X: =20
        Y: =compHeader_Settings.Height
        ZIndex: =2

        lblPromptTitle_Settings As label:
            BorderColor: =RGBA(0, 0, 0, 0)
            BorderStyle: =BorderStyle.None
            BorderThickness: =2
            Color: =ColorValue(varThemeColors.text)
            DisabledBorderColor: =RGBA(0, 0, 0, 0)
            FocusedBorderColor: =ColorValue(varThemeColors.primary)
            FocusedBorderThickness: =4
            Font: =varThemeFont.H2.face
            FontWeight: =varThemeFont.H2.weightBold
            Height: =Self.Size*4
            Italic: =varThemeFont.H2.italic
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingTop: =0
            Role: =TextRole.Heading1
            Size: =varThemeFont.H1.size
            Text: |-
                =// Define a variable named "Text" with the value "{value}"
                With(
                    {Text: "Settings"},
                    // Check if a localized text exists for "Text" in the user's preferred language
                    If(
                        // If the localized text is blank, return the default text
                        IsBlank(
                            LookUp(
                                colUserLocalizedStrings,
                                'English Value' = Text 
                            ).'Localized Value'
                        ),
                        Text,
                        // If a localized text is found, return that instead of the default text
                        LookUp(
                            colUserLocalizedStrings,
                            'English Value' = Text 
                        ).'Localized Value'
                    )
                )
            Width: =Parent.Width - 80
            X: =40
            ZIndex: =1

    compHeader_Settings As compHeader:
        HeaderComponentHeight: =75
        Height: =compHeader_Settings.HeaderComponentHeight
        IsOnSettingsScreen: =true
        MainPageScreen: ='Buddy Signup Screen'
        Width: =compHeader_Settings.HeaderComponentWidth
        ZIndex: =3

